#!/bin/sh
set -e

rm -f mednafen
rm -Rf fsbuild/_build

echo "Downloading mednafen-1.27.1.tar.xz..."
URL=https://mednafen.github.io/releases/files/mednafen-1.27.1.tar.xz
SHA256=f3a89b2f32f40c3232593808d05e0c21cbdf443688ace04c9c27e4cf4d5955fb
python3 fsbuild/download.py "$URL" sha256:$SHA256

echo "Extracting mednafen-1.27.1.tar.xz..."
mkdir -p fsbuild/_build
cd fsbuild/_build
tar xf ../_sources/mednafen-1.27.1.tar.xz
mv mednafen mednafen-src
