#!/bin/sh
set -e

python3 download.py \
https://mednafen.github.io/releases/files/mednafen-1.26.1.tar.xz \
sha256:842907c25c4292c9ba497c9cb9229c7d10e04e22cb4740d154ab690e6587fdf4

rm -Rf _build mednafen
rm -Rf mednafen
tar xf _sources/mednafen-1.26.1.tar.xz
mv mednafen _build
